### ISSUE TITLE
Reading a local video file from pywaggle Camera module in a loop.

### ISSUE THREAD

**Issue by RBhupi** [waggle-sensor/pywaggle#34]
Please, check the following issue.

### Ex.1: OpenCV
The following OpenCV code reads images from the mpg files in the loop.
 
```
import cv2
import matplotlib.pyplot as plt
infile = '/Users/bhupendra/projects/waggle/plugin-cmv-fftpc/test-data/sgptsimovieS01.a1.20160726.000000.mpg'
cap = cv2.VideoCapture(infile)
while True:
    ret, frame = cap.read()
    plt.imshow(frame, origin='lower')
    plt.show()
``` 

### Ex.2: pywaggle
The following code reads the first frame every time with a local file as input to the Camera.

It also uses a relative path.

```
from waggle.plugin import Plugin
from waggle.data.vision import Camera

import matplotlib.pyplot as plt

infile = 'file://test-data/sgptsimovieS01.a1.20160726.000000.mpg'
while True:
    with Plugin() as plugin, Camera(infile) as camera:
        sample = camera.snapshot()
        frame = sample.data
        plt.imshow(frame, origin='lower')
        plt.show()
        
```

Not a critical bug but affects the convenience of testing new features. If this can be made to have the same behavior as openCV with files, testing plugins on the local machines with custom data will be easy.

**Comment by seanshahkarami** [comment]
Good catch! I'll look into why snapshot behaves that way. In the mean time, are you able to use stream instead?

```python
from waggle.plugin import Plugin
from waggle.data.vision import Camera

import matplotlib.pyplot as plt

infile = 'file://test-data/sgptsimovieS01.a1.20160726.000000.mpg'
while True:
    with Plugin() as plugin, Camera(infile) as camera:
        for sample in camera.stream():
            frame = sample.data
            plt.imshow(frame, origin='lower')
            plt.show()
```

**Comment by seanshahkarami** [comment]
I took another look at your examples and noticed that in the second example, you open the camera _inside_ the while loop which is not really the same as the first example.

Try running the following example with the while / loop swapped and see if it works:

```python
from waggle.plugin import Plugin
from waggle.data.vision import Camera

import matplotlib.pyplot as plt

infile = 'file://test-data/sgptsimovieS01.a1.20160726.000000.mpg'
# swapped the loop and with
with Plugin() as plugin, Camera(infile) as camera:
    while True:
        sample = camera.snapshot()
        frame = sample.data
        plt.imshow(frame, origin='lower')
        plt.show()  
```

This works as expected for me with the latest pywaggle. (0.55.0)

**Comment by seanshahkarami** [comment]
Closing as example 2 works as expected after moving with statement outside the loop.
