### ISSUE TITLE
Decoder update

### ISSUE THREAD

**Issue by seonghapark** [waggle-sensor/pywaggle#4]
Some of decoded sensor values have more than 2 decimal points (e.g. 27.67333333333333).
Decoder needs to be changed to send only 2 decimal points for sensor values.

**Comment by seanshahkarami** [comment]
This is an easy fix. However, I'm curious if you think we should include the uncertainty in the data or meta data, then? (For example, 27.67 ± 0.005, where the 0.005 is recorded with the data somewhere.) Rounding off a number to represent our uncertainty seems like a *very* poor idea to me.

**Comment by seonghapark** [comment]
I agree that rounding off increase uncertainty, but long decimal point numbers are not that meaningful in terms of data analysis for temperature, humidity, and pressure. So we might can use 2 decimal points for the data.
